if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'SpahQL.Token.Boolean': { 'name': 'SpahQL.Token.Boolean', 'type': 'class', 'path': 'SpahQL/Token/Boolean/index.html' },
'SpahQL.Token': { 'name': 'SpahQL.Token', 'type': 'class', 'path': 'SpahQL/Token/index.html' },
'SpahQL.Callbacks.callbacks': { 'name': 'SpahQL.Callbacks.callbacks', 'type': 'class property', 'path': 'SpahQL/Callbacks/callbacks/index.html' },
'SpahQL#replaceAll': { 'name': 'SpahQL#replaceAll', 'type': 'instance method', 'path': 'SpahQL/prototype/replaceAll/index.html' },
'SpahQL.Token.SelectionQuery#useRoot': { 'name': 'SpahQL.Token.SelectionQuery#useRoot', 'type': 'instance property', 'path': 'SpahQL/Token/SelectionQuery/prototype/useRoot/index.html' },
'SpahQL.Token.PathComponent#key': { 'name': 'SpahQL.Token.PathComponent#key', 'type': 'instance property', 'path': 'SpahQL/Token/PathComponent/prototype/key/index.html' },
'SpahQL.Callbacks.pathModifiedOnObject': { 'name': 'SpahQL.Callbacks.pathModifiedOnObject', 'type': 'class method', 'path': 'SpahQL/Callbacks/pathModifiedOnObject/index.html' },
'SpahQL.DataHelper.mathGte': { 'name': 'SpahQL.DataHelper.mathGte', 'type': 'class method', 'path': 'SpahQL/DataHelper/mathGte/index.html' },
'new SpahQL.Token.Simple': { 'name': 'new SpahQL.Token.Simple', 'type': 'constructor', 'path': 'SpahQL/Token/Simple/new/index.html' },
'SpahQL.Errors': { 'name': 'SpahQL.Errors', 'type': 'class', 'path': 'SpahQL/Errors/index.html' },
'SpahQL.log': { 'name': 'SpahQL.log', 'type': 'class method', 'path': 'SpahQL/log/index.html' },
'SpahQL#map': { 'name': 'SpahQL#map', 'type': 'instance method', 'path': 'SpahQL/prototype/map/index.html' },
'SpahQL.Token.PathComponent#fetchResultsFromObjectByKey': { 'name': 'SpahQL.Token.PathComponent#fetchResultsFromObjectByKey', 'type': 'instance method', 'path': 'SpahQL/Token/PathComponent/prototype/fetchResultsFromObjectByKey/index.html' },
'SpahQL#concat': { 'name': 'SpahQL#concat', 'type': 'instance method', 'path': 'SpahQL/prototype/concat/index.html' },
'SpahQL.DataHelper.compare': { 'name': 'SpahQL.DataHelper.compare', 'type': 'class method', 'path': 'SpahQL/DataHelper/compare/index.html' },
'SpahQL.Token.Base.parseAt': { 'name': 'SpahQL.Token.Base.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/Base/parseAt/index.html' },
'SpahQL.Strategiser': { 'name': 'SpahQL.Strategiser', 'type': 'class', 'path': 'SpahQL/Strategiser/index.html' },
'SpahQL.Token#toSet': { 'name': 'SpahQL.Token#toSet', 'type': 'instance method', 'path': 'SpahQL/Token/prototype/toSet/index.html' },
'SpahQL.Token.PathComponent#recursive': { 'name': 'SpahQL.Token.PathComponent#recursive', 'type': 'instance property', 'path': 'SpahQL/Token/PathComponent/prototype/recursive/index.html' },
'SpahQL.Query#rawString': { 'name': 'SpahQL.Query#rawString', 'type': 'instance property', 'path': 'SpahQL/Query/prototype/rawString/index.html' },
'SpahQL.Query#assertion': { 'name': 'SpahQL.Query#assertion', 'type': 'instance property', 'path': 'SpahQL/Query/prototype/assertion/index.html' },
'SpahQL.QueryRunner.evalAssertion': { 'name': 'SpahQL.QueryRunner.evalAssertion', 'type': 'class method', 'path': 'SpahQL/QueryRunner/evalAssertion/index.html' },
'SpahQL#filter': { 'name': 'SpahQL#filter', 'type': 'instance method', 'path': 'SpahQL/prototype/filter/index.html' },
'SpahQL.Token.PathComponent#filterQueries': { 'name': 'SpahQL.Token.PathComponent#filterQueries', 'type': 'instance property', 'path': 'SpahQL/Token/PathComponent/prototype/filterQueries/index.html' },
'SpahQL.Token.FilterQuery#evaluate': { 'name': 'SpahQL.Token.FilterQuery#evaluate', 'type': 'instance method', 'path': 'SpahQL/Token/FilterQuery/prototype/evaluate/index.html' },
'SpahQL#clone': { 'name': 'SpahQL#clone', 'type': 'instance method', 'path': 'SpahQL/prototype/clone/index.html' },
'SpahQL#path': { 'name': 'SpahQL#path', 'type': 'instance method', 'path': 'SpahQL/prototype/path/index.html' },
'SpahQL.Token.parseAt': { 'name': 'SpahQL.Token.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/parseAt/index.html' },
'SpahQL.DataHelper.objectType': { 'name': 'SpahQL.DataHelper.objectType', 'type': 'class method', 'path': 'SpahQL/DataHelper/objectType/index.html' },
'SpahQL.result': { 'name': 'SpahQL.result', 'type': 'class method', 'path': 'SpahQL/result/index.html' },
'SpahQL#parents': { 'name': 'SpahQL#parents', 'type': 'instance method', 'path': 'SpahQL/prototype/parents/index.html' },
'SpahQL#keyNames': { 'name': 'SpahQL#keyNames', 'type': 'instance method', 'path': 'SpahQL/prototype/keyNames/index.html' },
'SpahQL.DataHelper.mathGt': { 'name': 'SpahQL.DataHelper.mathGt', 'type': 'class method', 'path': 'SpahQL/DataHelper/mathGt/index.html' },
'SpahQL.Token.SelectionQuery.parseAt': { 'name': 'SpahQL.Token.SelectionQuery.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/SelectionQuery/parseAt/index.html' },
'SpahQL#sourceData': { 'name': 'SpahQL#sourceData', 'type': 'instance method', 'path': 'SpahQL/prototype/sourceData/index.html' },
'SpahQL#value': { 'name': 'SpahQL#value', 'type': 'instance method', 'path': 'SpahQL/prototype/value/index.html' },
'SpahQL#assert': { 'name': 'SpahQL#assert', 'type': 'instance method', 'path': 'SpahQL/prototype/assert/index.html' },
'SpahQL.DataHelper.eqNumberRough': { 'name': 'SpahQL.DataHelper.eqNumberRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqNumberRough/index.html' },
'SpahQL.Token.Set#evaluate': { 'name': 'SpahQL.Token.Set#evaluate', 'type': 'instance method', 'path': 'SpahQL/Token/Set/prototype/evaluate/index.html' },
'SpahQL.Token.Simple#evaluate': { 'name': 'SpahQL.Token.Simple#evaluate', 'type': 'instance method', 'path': 'SpahQL/Token/Simple/prototype/evaluate/index.html' },
'SpahQL#paths': { 'name': 'SpahQL#paths', 'type': 'instance method', 'path': 'SpahQL/prototype/paths/index.html' },
'SpahQL.DataHelper.coerceKeyForObject': { 'name': 'SpahQL.DataHelper.coerceKeyForObject', 'type': 'class method', 'path': 'SpahQL/DataHelper/coerceKeyForObject/index.html' },
'SpahQL.Token.String': { 'name': 'SpahQL.Token.String', 'type': 'class', 'path': 'SpahQL/Token/String/index.html' },
'new SpahQL.Token.Set': { 'name': 'new SpahQL.Token.Set', 'type': 'constructor', 'path': 'SpahQL/Token/Set/new/index.html' },
'SpahQL.Token.SelectionQuery#pathComponents': { 'name': 'SpahQL.Token.SelectionQuery#pathComponents', 'type': 'instance property', 'path': 'SpahQL/Token/SelectionQuery/prototype/pathComponents/index.html' },
'SpahQL#parentPath': { 'name': 'SpahQL#parentPath', 'type': 'instance method', 'path': 'SpahQL/prototype/parentPath/index.html' },
'SpahQL.Token.PathComponent#evaluate': { 'name': 'SpahQL.Token.PathComponent#evaluate', 'type': 'instance method', 'path': 'SpahQL/Token/PathComponent/prototype/evaluate/index.html' },
'SpahQL.DataHelper.hashValues': { 'name': 'SpahQL.DataHelper.hashValues', 'type': 'class method', 'path': 'SpahQL/DataHelper/hashValues/index.html' },
'SpahQL.Token.ComparisonOperator': { 'name': 'SpahQL.Token.ComparisonOperator', 'type': 'class', 'path': 'SpahQL/Token/ComparisonOperator/index.html' },
'SpahQL#each': { 'name': 'SpahQL#each', 'type': 'instance method', 'path': 'SpahQL/prototype/each/index.html' },
'SpahQL.QueryParser.cleanQuery': { 'name': 'SpahQL.QueryParser.cleanQuery', 'type': 'class method', 'path': 'SpahQL/QueryParser/cleanQuery/index.html' },
'SpahQL.Query#comparisonOperator': { 'name': 'SpahQL.Query#comparisonOperator', 'type': 'instance property', 'path': 'SpahQL/Query/prototype/comparisonOperator/index.html' },
'SpahQL.DataHelper.ltSet': { 'name': 'SpahQL.DataHelper.ltSet', 'type': 'class method', 'path': 'SpahQL/DataHelper/ltSet/index.html' },
'SpahQL.Token.Numeric.parseAt': { 'name': 'SpahQL.Token.Numeric.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/Numeric/parseAt/index.html' },
'SpahQL.QueryParser.parseQuery': { 'name': 'SpahQL.QueryParser.parseQuery', 'type': 'class method', 'path': 'SpahQL/QueryParser/parseQuery/index.html' },
'SpahQL.QueryRunner': { 'name': 'SpahQL.QueryRunner', 'type': 'class', 'path': 'SpahQL/QueryRunner/index.html' },
'SpahQL#unlisten': { 'name': 'SpahQL#unlisten', 'type': 'instance method', 'path': 'SpahQL/prototype/unlisten/index.html' },
'SpahQL.Token.PathComponent#property': { 'name': 'SpahQL.Token.PathComponent#property', 'type': 'instance property', 'path': 'SpahQL/Token/PathComponent/prototype/property/index.html' },
'SpahQL_classExtend': { 'name': 'SpahQL_classExtend', 'type': 'class method', 'path': 'SpahQL_classExtend/index.html' },
'SpahQL#destroyAll': { 'name': 'SpahQL#destroyAll', 'type': 'instance method', 'path': 'SpahQL/prototype/destroyAll/index.html' },
'SpahQL.DataHelper': { 'name': 'SpahQL.DataHelper', 'type': 'class', 'path': 'SpahQL/DataHelper/index.html' },
'SpahQL#containingAll': { 'name': 'SpahQL#containingAll', 'type': 'instance method', 'path': 'SpahQL/prototype/containingAll/index.html' },
'SpahQL.Token.Set#evalStringRange': { 'name': 'SpahQL.Token.Set#evalStringRange', 'type': 'instance method', 'path': 'SpahQL/Token/Set/prototype/evalStringRange/index.html' },
'SpahQL.Callbacks.callbacksForPathInObject': { 'name': 'SpahQL.Callbacks.callbacksForPathInObject', 'type': 'class method', 'path': 'SpahQL/Callbacks/callbacksForPathInObject/index.html' },
'SpahQL#listen': { 'name': 'SpahQL#listen', 'type': 'instance method', 'path': 'SpahQL/prototype/listen/index.html' },
'SpahQL.DataHelper.jointSet': { 'name': 'SpahQL.DataHelper.jointSet', 'type': 'class method', 'path': 'SpahQL/DataHelper/jointSet/index.html' },
'SpahQL.DataHelper.gteSet': { 'name': 'SpahQL.DataHelper.gteSet', 'type': 'class method', 'path': 'SpahQL/DataHelper/gteSet/index.html' },
'SpahQL#destroy': { 'name': 'SpahQL#destroy', 'type': 'instance method', 'path': 'SpahQL/prototype/destroy/index.html' },
'SpahQL#keyName': { 'name': 'SpahQL#keyName', 'type': 'instance method', 'path': 'SpahQL/prototype/keyName/index.html' },
'SpahQL.Token.String.parseAt': { 'name': 'SpahQL.Token.String.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/String/parseAt/index.html' },
'SpahQL.Token.SelectionQuery#evaluate': { 'name': 'SpahQL.Token.SelectionQuery#evaluate', 'type': 'instance method', 'path': 'SpahQL/Token/SelectionQuery/prototype/evaluate/index.html' },
'SpahQL.DataHelper.eqHashRough': { 'name': 'SpahQL.DataHelper.eqHashRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqHashRough/index.html' },
'SpahQL#replace': { 'name': 'SpahQL#replace', 'type': 'instance method', 'path': 'SpahQL/prototype/replace/index.html' },
'SpahQL.Query#secondaryToken': { 'name': 'SpahQL.Query#secondaryToken', 'type': 'instance property', 'path': 'SpahQL/Query/prototype/secondaryToken/index.html' },
'SpahQL.DataHelper.modificationSymbol': { 'name': 'SpahQL.DataHelper.modificationSymbol', 'type': 'class method', 'path': 'SpahQL/DataHelper/modificationSymbol/index.html' },
'SpahQL.DataHelper.superSet': { 'name': 'SpahQL.DataHelper.superSet', 'type': 'class method', 'path': 'SpahQL/DataHelper/superSet/index.html' },
'SpahQL#first': { 'name': 'SpahQL#first', 'type': 'instance method', 'path': 'SpahQL/prototype/first/index.html' },
'SpahQL.QueryParser.queryCache': { 'name': 'SpahQL.QueryParser.queryCache', 'type': 'class property', 'path': 'SpahQL/QueryParser/queryCache/index.html' },
'SpahQL.Query#primaryToken': { 'name': 'SpahQL.Query#primaryToken', 'type': 'instance property', 'path': 'SpahQL/Query/prototype/primaryToken/index.html' },
'SpahQL.Token.KeyName.parseAt': { 'name': 'SpahQL.Token.KeyName.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/KeyName/parseAt/index.html' },
'SpahQL.QueryParser': { 'name': 'SpahQL.QueryParser', 'type': 'class', 'path': 'SpahQL/QueryParser/index.html' },
'SpahQL.select': { 'name': 'SpahQL.select', 'type': 'class method', 'path': 'SpahQL/select/index.html' },
'SpahQL.QueryParser.throwParseErrorAt': { 'name': 'SpahQL.QueryParser.throwParseErrorAt', 'type': 'class method', 'path': 'SpahQL/QueryParser/throwParseErrorAt/index.html' },
'SpahQL.Token.Numeric': { 'name': 'SpahQL.Token.Numeric', 'type': 'class', 'path': 'SpahQL/Token/Numeric/index.html' },
'SpahQL.DataHelper.truthySet': { 'name': 'SpahQL.DataHelper.truthySet', 'type': 'class method', 'path': 'SpahQL/DataHelper/truthySet/index.html' },
'new SpahQL.Token.PathComponent': { 'name': 'new SpahQL.Token.PathComponent', 'type': 'constructor', 'path': 'SpahQL/Token/PathComponent/new/index.html' },
'SpahQL.DataHelper.lteSet': { 'name': 'SpahQL.DataHelper.lteSet', 'type': 'class method', 'path': 'SpahQL/DataHelper/lteSet/index.html' },
'SpahQL.QueryRunner.select': { 'name': 'SpahQL.QueryRunner.select', 'type': 'class method', 'path': 'SpahQL/QueryRunner/select/index.html' },
'SpahQL.Token.Set#tokens': { 'name': 'SpahQL.Token.Set#tokens', 'type': 'instance property', 'path': 'SpahQL/Token/Set/prototype/tokens/index.html' },
'SpahQL#values': { 'name': 'SpahQL#values', 'type': 'instance method', 'path': 'SpahQL/prototype/values/index.html' },
'SpahQL.DataHelper.eqArrayRough': { 'name': 'SpahQL.DataHelper.eqArrayRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqArrayRough/index.html' },
'SpahQL.Token.FilterQuery.parseAt': { 'name': 'SpahQL.Token.FilterQuery.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/FilterQuery/parseAt/index.html' },
'SpahQL.Token.ComparisonOperator.parseAt': { 'name': 'SpahQL.Token.ComparisonOperator.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/ComparisonOperator/parseAt/index.html' },
'SpahQL.Token.PathComponent': { 'name': 'SpahQL.Token.PathComponent', 'type': 'class', 'path': 'SpahQL/Token/PathComponent/index.html' },
'SpahQL.Callbacks': { 'name': 'SpahQL.Callbacks', 'type': 'class', 'path': 'SpahQL/Callbacks/index.html' },
'SpahQL.Token.Boolean.parseAt': { 'name': 'SpahQL.Token.Boolean.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/Boolean/parseAt/index.html' },
'SpahQL.DataHelper.eqSetStrict': { 'name': 'SpahQL.DataHelper.eqSetStrict', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqSetStrict/index.html' },
'SpahQL.DataHelper.jointSetWithCallback': { 'name': 'SpahQL.DataHelper.jointSetWithCallback', 'type': 'class method', 'path': 'SpahQL/DataHelper/jointSetWithCallback/index.html' },
'SpahQL.verbose': { 'name': 'SpahQL.verbose', 'type': 'class property', 'path': 'SpahQL/verbose/index.html' },
'SpahQL#parentPaths': { 'name': 'SpahQL#parentPaths', 'type': 'instance method', 'path': 'SpahQL/prototype/parentPaths/index.html' },
'SpahQL#select': { 'name': 'SpahQL#select', 'type': 'instance method', 'path': 'SpahQL/prototype/select/index.html' },
'SpahQL.DataHelper.deepClone': { 'name': 'SpahQL.DataHelper.deepClone', 'type': 'class method', 'path': 'SpahQL/DataHelper/deepClone/index.html' },
'SpahQL#types': { 'name': 'SpahQL#types', 'type': 'instance method', 'path': 'SpahQL/prototype/types/index.html' },
'SpahQL.Token.Set#isRange': { 'name': 'SpahQL.Token.Set#isRange', 'type': 'instance property', 'path': 'SpahQL/Token/Set/prototype/isRange/index.html' },
'SpahQL#item': { 'name': 'SpahQL#item', 'type': 'instance method', 'path': 'SpahQL/prototype/item/index.html' },
'SpahQL.assert': { 'name': 'SpahQL.assert', 'type': 'class method', 'path': 'SpahQL/assert/index.html' },
'SpahQL.DataHelper.gtSet': { 'name': 'SpahQL.DataHelper.gtSet', 'type': 'class method', 'path': 'SpahQL/DataHelper/gtSet/index.html' },
'SpahQL.Token.Set.parseAt': { 'name': 'SpahQL.Token.Set.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/Set/parseAt/index.html' },
'SpahQL.Query': { 'name': 'SpahQL.Query', 'type': 'class', 'path': 'SpahQL/Query/index.html' },
'SpahQL_classRegister': { 'name': 'SpahQL_classRegister', 'type': 'class method', 'path': 'SpahQL_classRegister/index.html' },
'SpahQL.DataHelper.mathCompare': { 'name': 'SpahQL.DataHelper.mathCompare', 'type': 'class method', 'path': 'SpahQL/DataHelper/mathCompare/index.html' },
'SpahQL.QueryRunner.assert': { 'name': 'SpahQL.QueryRunner.assert', 'type': 'class method', 'path': 'SpahQL/QueryRunner/assert/index.html' },
'SpahQL.DataHelper.eqBooleanRough': { 'name': 'SpahQL.DataHelper.eqBooleanRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqBooleanRough/index.html' },
'SpahQL.DataHelper.mathLte': { 'name': 'SpahQL.DataHelper.mathLte', 'type': 'class method', 'path': 'SpahQL/DataHelper/mathLte/index.html' },
'new SpahQL.Token.SelectionQuery': { 'name': 'new SpahQL.Token.SelectionQuery', 'type': 'constructor', 'path': 'SpahQL/Token/SelectionQuery/new/index.html' },
'SpahQL.Token.SelectionQuery': { 'name': 'SpahQL.Token.SelectionQuery', 'type': 'class', 'path': 'SpahQL/Token/SelectionQuery/index.html' },
'SpahQL.DataHelper.eqStringRough': { 'name': 'SpahQL.DataHelper.eqStringRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqStringRough/index.html' },
'SpahQL.isHeadless': { 'name': 'SpahQL.isHeadless', 'type': 'class method', 'path': 'SpahQL/isHeadless/index.html' },
'SpahQL#setAll': { 'name': 'SpahQL#setAll', 'type': 'instance method', 'path': 'SpahQL/prototype/setAll/index.html' },
'SpahQL.Token.Set#evalNumericRange': { 'name': 'SpahQL.Token.Set#evalNumericRange', 'type': 'instance method', 'path': 'SpahQL/Token/Set/prototype/evalNumericRange/index.html' },
'SpahQL.DataHelper.eq': { 'name': 'SpahQL.DataHelper.eq', 'type': 'class method', 'path': 'SpahQL/DataHelper/eq/index.html' },
'SpahQL.db': { 'name': 'SpahQL.db', 'type': 'class method', 'path': 'SpahQL/db/index.html' },
'SpahQL.Token.Simple': { 'name': 'SpahQL.Token.Simple', 'type': 'class', 'path': 'SpahQL/Token/Simple/index.html' },
'SpahQL.Token.throwParseErrorAt': { 'name': 'SpahQL.Token.throwParseErrorAt', 'type': 'class method', 'path': 'SpahQL/Token/throwParseErrorAt/index.html' },
'SpahQL#detach': { 'name': 'SpahQL#detach', 'type': 'instance method', 'path': 'SpahQL/prototype/detach/index.html' },
'SpahQL#set': { 'name': 'SpahQL#set', 'type': 'instance method', 'path': 'SpahQL/prototype/set/index.html' },
'SpahQL.Token.PathComponent.parseAt': { 'name': 'SpahQL.Token.PathComponent.parseAt', 'type': 'class method', 'path': 'SpahQL/Token/PathComponent/parseAt/index.html' },
'SpahQL.Errors.SpahQLRunTimeError': { 'name': 'SpahQL.Errors.SpahQLRunTimeError', 'type': 'class', 'path': 'SpahQL/Errors/SpahQLRunTimeError/index.html' },
'SpahQL.Token.Set': { 'name': 'SpahQL.Token.Set', 'type': 'class', 'path': 'SpahQL/Token/Set/index.html' },
'SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty': { 'name': 'SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty', 'type': 'instance method', 'path': 'SpahQL/Token/PathComponent/prototype/fetchResultsFromObjectByProperty/index.html' },
'SpahQL.Token.FilterQuery': { 'name': 'SpahQL.Token.FilterQuery', 'type': 'class', 'path': 'SpahQL/Token/FilterQuery/index.html' },
'SpahQL#type': { 'name': 'SpahQL#type', 'type': 'instance method', 'path': 'SpahQL/prototype/type/index.html' },
'SpahQL.Token.KeyName': { 'name': 'SpahQL.Token.KeyName', 'type': 'class', 'path': 'SpahQL/Token/KeyName/index.html' },
'SpahQL_classCreate': { 'name': 'SpahQL_classCreate', 'type': 'class method', 'path': 'SpahQL_classCreate/index.html' },
'SpahQL.Token.Base': { 'name': 'SpahQL.Token.Base', 'type': 'class', 'path': 'SpahQL/Token/Base/index.html' },
'SpahQL#last': { 'name': 'SpahQL#last', 'type': 'instance method', 'path': 'SpahQL/prototype/last/index.html' },
'SpahQL.DataHelper.hashKeys': { 'name': 'SpahQL.DataHelper.hashKeys', 'type': 'class method', 'path': 'SpahQL/DataHelper/hashKeys/index.html' },
'new SpahQL': { 'name': 'new SpahQL', 'type': 'constructor', 'path': 'SpahQL/new/index.html' },
'SpahQL.inBrowser': { 'name': 'SpahQL.inBrowser', 'type': 'class method', 'path': 'SpahQL/inBrowser/index.html' },
'SpahQL#resultModified': { 'name': 'SpahQL#resultModified', 'type': 'instance method', 'path': 'SpahQL/prototype/resultModified/index.html' },
'SpahQL.DataHelper.mathLt': { 'name': 'SpahQL.DataHelper.mathLt', 'type': 'class method', 'path': 'SpahQL/DataHelper/mathLt/index.html' },
'SpahQL#containing': { 'name': 'SpahQL#containing', 'type': 'instance method', 'path': 'SpahQL/prototype/containing/index.html' },
'SpahQL.DataHelper.eqSetRough': { 'name': 'SpahQL.DataHelper.eqSetRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqSetRough/index.html' },
'SpahQL.DataHelper.eqRough': { 'name': 'SpahQL.DataHelper.eqRough', 'type': 'class method', 'path': 'SpahQL/DataHelper/eqRough/index.html' },
'SpahQL#parent': { 'name': 'SpahQL#parent', 'type': 'instance method', 'path': 'SpahQL/prototype/parent/index.html' },
'SpahQL.Errors.SpahQLError': { 'name': 'SpahQL.Errors.SpahQLError', 'type': 'class', 'path': 'SpahQL/Errors/SpahQLError/index.html' },
'SpahQL': { 'name': 'SpahQL', 'type': 'class', 'path': 'SpahQL/index.html' }
};